// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'ArticleDetail': typeof import('../components/article-detail.vue')['default'],
    'Article': typeof import('../components/article.vue')['default'],
    'Links': typeof import('../components/links.vue')['default'],
    'Menu': typeof import('../components/menu.vue')['default'],
    'Sidebar': typeof import('../components/sidebar.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default']
  }
}
export {}
